title: Alicja Kolasinska
logo: https://avatars.githubusercontent.com/u/192789028?v=4
description: >
  <br>
  Psychologist by education, data scientist by passion. Books, coffee and cooking aficionado from 5 to 9
  <br><br>
  <a href="https://www.linkedin.com/in/alicja-kolasinska-5354101a1/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
