title: Alicja
logo: <href="https://avatars.githubusercontent.com/u/192789028?v=4">
description:
First description
Psychologist by education, data scientist by passion
<a href="https://www.linkedin.com/in/alicja-kolasinska-5354101a1/"›View My LinkedIn Profile</a›

remote_theme: pages-themes/minimal@v0.2.0
plugins: - jekyll-remote-theme 
